### PR TITLE
Fix migration

### LINKED ISSUE #948: no such column: save_in_public_storage (code 1 SQLITE_ERROR)
Thank you for the awsome library. I've been using it since version 1.6.1.
**Describe the bug**
When updating an Android app from version 1.6.1 to 1.11.7, an error occurs stating that the column cannot be found.

**To Reproduce**

```
java.util.concurrent.ExecutionException: android.database.sqlite.SQLiteException: no such column: save_in_public_storage (code 1 SQLITE_ERROR): , while compiling: SELECT _id, task_id, progress, status, url, file_name, saved_dir, headers, mime_type, resumable, open_file_from_notification, show_notification, time_created, save_in_public_storage, allow_cellular FROM task WHERE task_id = ? ORDER BY _id DESC LIMIT 1
                                                                                                    	at androidx.work.impl.utils.futures.a.i(SourceFile:21)
                                                                                                    	at androidx.work.impl.utils.futures.a.get(SourceFile:48)
                                                                                                    	at r0.k$b.run(SourceFile:5)
                                                                                                    	at z0.k$a.run(SourceFile:3)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.database.sqlite.SQLiteException: no such column: save_in_public_storage (code 1 SQLITE_ERROR): , while compiling: SELECT _id, task_id, progress, status, url, file_name, saved_dir, headers, mime_type, resumable, open_file_from_notification, show_notification, time_created, save_in_public_storage, allow_cellular FROM task WHERE task_id = ? ORDER BY _id DESC LIMIT 1
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.-$$Nest$smnativePrepareStatement(Unknown Source:0)
                                                                                                    	at android.database.sqlite.SQLiteConnection$PreparedStatementCache.createStatement(SQLiteConnection.java:1552)
                                                                                                    	at android.database.sqlite.SQLiteConnection.acquirePreparedStatementLI(SQLiteConnection.java:1095)
                                                                                                    	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1123)
                                                                                                    	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:683)
                                                                                                    	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:614)
                                                                                                    	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
                                                                                                    	at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                                                    	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1818)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1650)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1507)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1733)
                                                                                                    	at q7.i.d(SourceFile:28)
                                                                                                    	at vn.hunghd.flutterdownloader.DownloadWorker.r(SourceFile:205)
                                                                                                    	at androidx.work.Worker$a.run(SourceFile:3)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012) 
```

1. use v1.6.1
2. download something
3. use v1.11.7
4. download something
5. can't start downloading

**Expected behavior**
update v1.6.1 to v1.11.7, can download something.

- Device: Pixel7
- OS: Android 14
- plugin version v1.6.1 to v1.11.7

### PR DESCRIPTION
**Pull request by bowyer-app**
close #948

### CODE REVIEW

File: android/src/main/kotlin/vn/hunghd/flutterdownloader/TaskDbHelper.kt [hunk 1]
```diff
@@ -12,14 +12,31 @@ class TaskDbHelper private constructor(context: Context) :
...
+        update2to3(db, oldVersion)
+        update3to4(db, oldVersion)
+    }
+
+    private fun update1to2(db: SQLiteDatabase, oldVersion: Int) {
+        if (oldVersion > 1) {
+            return
+        }
+        db.execSQL(SQL_DELETE_ENTRIES)
+        onCreate(db)
```
Comment (bowyer-app) [inline android/src/main/kotlin/vn/hunghd/flutterdownloader/TaskDbHelper.kt:25]: In the old version, this was executed when updating from 1 to 2, so I think it will work now.
https://github.com/fluttercommunity/flutter_downloader/blob/v1.6.1/android/src/main/java/vn/hunghd/flutterdownloader/TaskDbHelper.java#L59-L60

**Comment by bowyer-app** [comment]
Hello　@bartekpacia @salmaahhmed 

I hope you're doing well. I would greatly appreciate it if you could take the time to review it. 

Thank you in advance!

Best regards

**Comment by bowyer-app** [comment]
@bartekpacia @salmaahhmed

I know you're busy, but could you please review this for me?

**Comment by bartekpacia** [comment]
hey @bowyer-app, sorry for the delay. I'll try to get to it in the weekend. I'm indeed busy.

**Comment by bowyer-app** [comment]
@bartekpacia
Thank you. I'm looking forward to the good news.

**Comment by bowyer-app** [comment]
Hi @bartekpacia, I hope you're doing well. I just wanted to kindly follow up on this PR that we discussed a while ago. I understand you might be busy, but it would be great if you could let me know when you might have a chance to look into it. Thank you for your time!

**Review by salmaahhmed — APPROVED** [review]
